services:
  mongo:
    image: mongo:7
    ports: 
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
  
  node:
    build:
      context: .
      dockerfile: backend/DockerFile
    ports:
      - "5002:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
volumes:
  mongo-data:
    driver: local